import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common'; import { Prisma } from '@prisma/client'; import { PrismaService } from '../../core/database/prisma.service'; import { AddMaterialDto,AddTimeDto,CreateServiceOrderDto,InvoiceServiceOrderDto } from './dto/services.dto';
@Injectable() export class ServicesService { constructor(private p:PrismaService){}
 async create(c:string,d:CreateServiceOrderDto){ const [b,cu]=await Promise.all([this.p.branch.findFirst({where:{id:d.branchId,companyId:c,deletedAt:null}}),this.p.customer.findFirst({where:{id:d.customerId,companyId:c,deletedAt:null}})]); if(!b||!cu) throw new BadRequestException('Filial ou cliente inválido.'); return this.p.serviceOrder.create({data:{companyId:c,...d},include:this.inc()}); }
 list(c:string){return this.p.serviceOrder.findMany({where:{companyId:c},orderBy:{createdAt:'desc'},include:this.inc()})}
 async one(c:string,id:string){const x=await this.p.serviceOrder.findFirst({where:{id,companyId:c},include:this.inc()});if(!x)throw new NotFoundException('OS não encontrada.');return x}
 async start(c:string,id:string){const x=await this.one(c,id);if(!['DRAFT','OPEN'].includes(x.status))throw new BadRequestException('OS não pode ser iniciada.');return this.p.serviceOrder.update({where:{id},data:{status:'IN_PROGRESS',startedAt:new Date()},include:this.inc()})}
 async material(c:string,id:string,d:AddMaterialDto){const os=await this.one(c,id);if(os.status!=='IN_PROGRESS')throw new BadRequestException('OS deve estar em andamento.');return this.p.$transaction(async tx=>{const product=await tx.product.findFirst({where:{id:d.productId,companyId:c,deletedAt:null}});const bal=await tx.inventoryBalance.findUnique({where:{branchId_productId:{branchId:os.branchId,productId:d.productId}}});const q=new Prisma.Decimal(d.quantity);if(!product||!bal||bal.available.lessThan(q))throw new BadRequestException('Estoque insuficiente para material da OS.');const prev=bal.quantity, cur=prev.sub(q);await tx.inventoryBalance.update({where:{id:bal.id},data:{quantity:cur,available:bal.available.sub(q)}});await tx.inventoryMovement.create({data:{companyId:c,branchId:os.branchId,productId:d.productId,type:'EXIT',quantity:q,previousQty:prev,currentQty:cur,referenceType:'SERVICE_ORDER',referenceId:id,notes:`Consumo OS ${os.number}`}});const total=q.mul(product.costPrice);await tx.serviceOrderMaterial.create({data:{serviceOrderId:id,productId:d.productId,quantity:q,unitCost:product.costPrice,totalAmount:total}});return tx.serviceOrder.update({where:{id},data:{materialAmount:{increment:total},totalAmount:{increment:total}},include:this.inc()});});}
 async time(c:string,id:string,currentUser:string,d:AddTimeDto){const os=await this.one(c,id);if(os.status!=='IN_PROGRESS')throw new BadRequestException('OS deve estar em andamento.');const total=new Prisma.Decimal(d.hourlyRate).mul(d.minutes).div(60);return this.p.$transaction(async tx=>{await tx.serviceTimeEntry.create({data:{serviceOrderId:id,userId:d.userId??currentUser,minutes:d.minutes,hourlyRate:d.hourlyRate,totalAmount:total,notes:d.notes}});return tx.serviceOrder.update({where:{id},data:{laborAmount:{increment:total},totalAmount:{increment:total}},include:this.inc()});});}
 async complete(c:string,id:string){const os=await this.one(c,id);if(os.status!=='IN_PROGRESS')throw new BadRequestException('OS deve estar em andamento.');return this.p.serviceOrder.update({where:{id},data:{status:'COMPLETED',completedAt:new Date()},include:this.inc()})}
 async invoice(c:string,id:string,d:InvoiceServiceOrderDto){const os=await this.one(c,id);if(os.status!=='COMPLETED')throw new BadRequestException('OS deve estar concluída.');if(os.saleId)throw new BadRequestException('OS já faturada.');return this.p.$transaction(async tx=>{const sale=await tx.sale.create({data:{companyId:c,branchId:os.branchId,customerId:os.customerId,paymentTermId:d.paymentTermId,number:d.saleNumber,status:'CONFIRMED',totalAmount:os.totalAmount,notes:`Faturamento da OS ${os.number}`}});await tx.financialEntry.create({data:{companyId:c,branchId:os.branchId,type:'RECEIVABLE',status:'OPEN',description:`OS ${os.number}`,amount:os.totalAmount,dueDate:new Date(),customerId:os.customerId,referenceType:'SERVICE_ORDER',referenceId:id}});return tx.serviceOrder.update({where:{id},data:{status:'INVOICED',saleId:sale.id},include:this.inc()});});}
 inc(){return {branch:{select:{id:true,name:true}},customer:{select:{id:true,name:true}},assignedUser:{select:{id:true,name:true}},materials:{include:{product:{select:{id:true,name:true,sku:true}}}},timeEntries:{include:{user:{select:{id:true,name:true}}}},sale:true} as const}
}
