import { createContext, PropsWithChildren, ReactNode, useContext, useEffect, useState } from 'react';

type ToastKind='success'|'error'|'info';
type Toast={id:number;message:string;kind:ToastKind};
const ToastContext=createContext<{show:(message:string,kind?:ToastKind)=>void}>({show:()=>{}});
export function ToastProvider({children}:PropsWithChildren){const[toasts,setToasts]=useState<Toast[]>([]);function show(message:string,kind:ToastKind='success'){const id=Date.now()+Math.random();setToasts(v=>[...v,{id,message,kind}]);setTimeout(()=>setToasts(v=>v.filter(x=>x.id!==id)),3500)}return <ToastContext.Provider value={{show}}>{children}<div className="toast-stack" aria-live="polite">{toasts.map(t=><div key={t.id} className={`toast ${t.kind}`}><span>{t.kind==='success'?'✓':t.kind==='error'?'!':'i'}</span><p>{t.message}</p><button onClick={()=>setToasts(v=>v.filter(x=>x.id!==t.id))}>×</button></div>)}</div></ToastContext.Provider>}
export const useToast=()=>useContext(ToastContext);

export function ConfirmDialog({open,title,description,confirmLabel='Confirmar',danger=false,onConfirm,onCancel}:{open:boolean;title:string;description?:string;confirmLabel?:string;danger?:boolean;onConfirm:()=>void|Promise<void>;onCancel:()=>void}){const[busy,setBusy]=useState(false);useEffect(()=>{if(!open)setBusy(false)},[open]);if(!open)return null;async function go(){setBusy(true);try{await onConfirm()}finally{setBusy(false)}}return <div className="modal-backdrop" onMouseDown={onCancel}><div className="confirm-dialog" onMouseDown={e=>e.stopPropagation()}><div className={`confirm-icon ${danger?'danger':''}`}>{danger?'!':'?'}</div><h3>{title}</h3>{description&&<p>{description}</p>}<div className="modal-actions"><button className="ghost-button" onClick={onCancel} disabled={busy}>Cancelar</button><button className={danger?'danger-button':'primary-button'} onClick={go} disabled={busy}>{busy?'Processando...':confirmLabel}</button></div></div></div>}

export function Pagination({page,totalPages,onPage}:{page:number;totalPages:number;onPage:(p:number)=>void}){if(totalPages<=1)return null;return <div className="pagination"><button disabled={page<=1} onClick={()=>onPage(page-1)}>← Anterior</button><span>Página <strong>{page}</strong> de {totalPages}</span><button disabled={page>=totalPages} onClick={()=>onPage(page+1)}>Próxima →</button></div>}
export function SkeletonTable({rows=6}:{rows?:number}){return <div className="skeleton-table">{Array.from({length:rows}).map((_,i)=><div className="skeleton-row" key={i}><i/><i/><i/><i/></div>)}</div>}
export function DetailDrawer({open,title,children,onClose}:{open:boolean;title:string;children:ReactNode;onClose:()=>void}){if(!open)return null;return <><div className="drawer-backdrop" onClick={onClose}/><aside className="detail-drawer"><div className="drawer-header"><div><span className="eyebrow">Detalhes</span><h2>{title}</h2></div><button className="icon-button" onClick={onClose}>×</button></div><div className="drawer-body">{children}</div></aside></>}
