import { useCallback, useEffect, useState } from 'react';
import { api } from '../lib/api';
import { Alert, Badge, Card, Empty, PageHeader } from '../components/Ui';
import { DetailDrawer, Pagination, SkeletonTable } from '../components/Ux';

type Kind='inventory'|'purchases'|'sales'|'finance';
const cfg:any={inventory:{title:'Estoque',subtitle:'Saldos por produto e filial',url:'/inventory',cols:['Produto','Filial','Quantidade','Reservado','Disponível']},purchases:{title:'Compras',subtitle:'Acompanhamento das compras e fornecedores',url:'/purchases',cols:['Número','Fornecedor','Data','Total','Status']},sales:{title:'Vendas',subtitle:'Vendas, clientes e faturamento',url:'/sales',cols:['Número','Cliente','Data','Total','Status']},finance:{title:'Financeiro',subtitle:'Contas a receber e a pagar',url:'/finance/entries',cols:['Descrição','Tipo','Vencimento','Valor','Pago','Status']}};
const money=(v:any)=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});const date=(v:any)=>v?new Date(v).toLocaleDateString('pt-BR'):'-';
export function DataTablePage({kind}:{kind:Kind}){const c=cfg[kind];const[rows,setRows]=useState<any[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[search,setSearch]=useState('');const[debounced,setDebounced]=useState('');const[detail,setDetail]=useState<any|null>(null);const[page,setPage]=useState(1);const pageSize=12;
 useEffect(()=>{const t=setTimeout(()=>setDebounced(search.trim()),300);return()=>clearTimeout(t)},[search]);const load=useCallback(async()=>{setLoading(true);setError('');try{const q=debounced?`?search=${encodeURIComponent(debounced)}`:'';const r:any=await api(c.url+q);setRows(r.data||r)}catch(e){setError(e instanceof Error?e.message:'Erro ao carregar')}finally{setLoading(false)}},[c.url,debounced]);useEffect(()=>{setPage(1);void load()},[load]);
 function cells(r:any){if(kind==='inventory')return [<><strong>{r.product?.name}</strong><small>{r.product?.sku}</small></>,r.branch?.name,Number(r.quantity),Number(r.reserved),Number(r.available)];if(kind==='purchases')return [r.number,r.supplier?.name,date(r.issueDate),money(r.totalAmount),<Badge value={r.status}/>];if(kind==='sales')return [r.number,r.customer?.name,date(r.issueDate),money(r.totalAmount),<Badge value={r.status}/>];return [<><strong>{r.description||r.referenceType||'Lançamento'}</strong><small>{r.installmentNumber?`Parcela ${r.installmentNumber}`:''}</small></>,r.type,date(r.dueDate),money(r.amount),money(r.paidAmount),<Badge value={r.status}/>]}
 const totalPages=Math.max(1,Math.ceil(rows.length/pageSize));const visible=rows.slice((page-1)*pageSize,page*pageSize);const detailMap=detail?(kind==='inventory'?{'Produto':detail.product?.name,'SKU':detail.product?.sku,'Filial':detail.branch?.name,'Quantidade':detail.quantity,'Reservado':detail.reserved,'Disponível':detail.available}:kind==='purchases'?{'Número':detail.number,'Fornecedor':detail.supplier?.name,'Emissão':date(detail.issueDate),'Total':money(detail.totalAmount),'Status':detail.status}:kind==='sales'?{'Número':detail.number,'Cliente':detail.customer?.name,'Emissão':date(detail.issueDate),'Total':money(detail.totalAmount),'Status':detail.status}:{'Descrição':detail.description||detail.referenceType,'Tipo':detail.type,'Vencimento':date(detail.dueDate),'Valor':money(detail.amount),'Pago':money(detail.paidAmount),'Status':detail.status}):{};
 return <><PageHeader title={c.title} subtitle={c.subtitle}/><Card><div className="toolbar"><div className="search"><span>⌕</span><input placeholder={`Buscar em ${c.title.toLowerCase()}...`} value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="toolbar-right"><span className="record-count">{rows.length} registro{rows.length===1?'':'s'}</span><button className="ghost-button" onClick={load}>↻ Atualizar</button></div></div>{error&&<Alert>{error}</Alert>}{loading?<SkeletonTable/>:rows.length===0?<Empty text={search?'Nenhum resultado para esta busca.':'Nenhum registro encontrado.'}/>:<><div className="table-wrap"><table><thead><tr>{c.cols.map((x:string)=><th key={x}>{x}</th>)}</tr></thead><tbody>{visible.map((r:any)=><tr key={r.id} className="clickable-row" onClick={()=>setDetail(r)}>{cells(r).map((v:any,i:number)=><td key={i}>{v}</td>)}</tr>)}</tbody></table></div><Pagination page={page} totalPages={totalPages} onPage={setPage}/></>}</Card><DetailDrawer open={!!detail} title={kind==='inventory'?detail?.product?.name:detail?.number||detail?.description||c.title} onClose={()=>setDetail(null)}><div className="detail-list">{Object.entries(detailMap).map(([k,v])=><div key={k}><span>{k}</span><strong>{String(v??'-')}</strong></div>)}</div></DetailDrawer></>}
