import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import { api } from '../lib/api';
import { useAuth } from '../context/AuthContext';
import { Alert, Badge, Card, Empty, PageHeader } from '../components/Ui';
import { ConfirmDialog, DetailDrawer, Pagination, SkeletonTable, useToast } from '../components/Ux';

type Kind='customers'|'suppliers'|'products';
const configs={
 customers:{title:'Clientes',single:'Cliente',subtitle:'Cadastro e gestão da base de clientes',permission:'customers',endpoint:'/customers',fields:[['type','Tipo','select'],['name','Nome','text'],['document','CPF/CNPJ','text'],['email','E-mail','email'],['phone','Telefone','text']]},
 suppliers:{title:'Fornecedores',single:'Fornecedor',subtitle:'Cadastro de parceiros e fornecedores',permission:'suppliers',endpoint:'/suppliers',fields:[['type','Tipo','select'],['name','Nome','text'],['document','CPF/CNPJ','text'],['email','E-mail','email'],['phone','Telefone','text']]},
 products:{title:'Produtos',single:'Produto',subtitle:'Catálogo de produtos, preços e estoque mínimo',permission:'products',endpoint:'/products',fields:[['name','Nome','text'],['sku','SKU','text'],['barcode','Código de barras','text'],['unit','Unidade','unit'],['costPrice','Custo','number'],['salePrice','Venda','number'],['minimumStock','Estoque mínimo','number']]}
} as const;
const initial=(kind:Kind)=>kind==='products'?{name:'',sku:'',barcode:'',unit:'UN',costPrice:'0',salePrice:'0',minimumStock:'0'}:{type:kind==='suppliers'?'BUSINESS':'INDIVIDUAL',name:'',document:'',email:'',phone:''};
const money=(v:any)=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
export function MasterDataPage({kind}:{kind:Kind}){
 const c=configs[kind]; const {can}=useAuth(); const toast=useToast(); const [rows,setRows]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [search,setSearch]=useState(''); const [debounced,setDebounced]=useState(''); const [open,setOpen]=useState(false); const [editing,setEditing]=useState<any|null>(null); const [detail,setDetail]=useState<any|null>(null); const [remove,setRemove]=useState<any|null>(null); const [form,setForm]=useState<any>(()=>initial(kind)); const [error,setError]=useState(''); const[page,setPage]=useState(1); const pageSize=10;
 useEffect(()=>{const t=setTimeout(()=>setDebounced(search.trim()),300);return()=>clearTimeout(t)},[search]);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const q=debounced?`?search=${encodeURIComponent(debounced)}`:'';const r:any=await api(c.endpoint+q);setRows(r.data||r);}catch(e){setError(e instanceof Error?e.message:'Erro ao carregar.')}finally{setLoading(false)}},[c.endpoint,debounced]);
 useEffect(()=>{setPage(1);void load()},[load]); useEffect(()=>{setForm(initial(kind));setEditing(null);setDetail(null)},[kind]);
 async function submit(e:FormEvent){e.preventDefault();setError('');try{const body:any={...form};if(kind==='products'){for(const k of ['costPrice','salePrice','minimumStock'])body[k]=Number(body[k]||0);if(!body.barcode)delete body.barcode;}if(!body.email)delete body.email;if(!body.phone)delete body.phone;await api(editing?`${c.endpoint}/${editing.id}`:c.endpoint,{method:editing?'PATCH':'POST',body:JSON.stringify(body)});toast.show(`${c.single} ${editing?'atualizado':'criado'} com sucesso.`);closeForm();await load();}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar.')}}
 function closeForm(){setOpen(false);setEditing(null);setForm(initial(kind))} function edit(r:any){setEditing(r);setForm(kind==='products'?{name:r.name||'',sku:r.sku||'',barcode:r.barcode||'',unit:r.unit||'UN',costPrice:String(r.costPrice||0),salePrice:String(r.salePrice||0),minimumStock:String(r.minimumStock||0)}:{type:r.type||'INDIVIDUAL',name:r.name||'',document:r.document||'',email:r.email||'',phone:r.phone||''});setOpen(true)}
 async function removeRecord(){if(!remove)return;try{await api(`${c.endpoint}/${remove.id}`,{method:'DELETE'});toast.show(`${c.single} inativado com sucesso.`);setRemove(null);await load()}catch(e){toast.show(e instanceof Error?e.message:'Não foi possível inativar.','error')}}
 const columns=useMemo(()=>kind==='products'?['Produto','SKU','Unidade','Preço','Status','']:['Nome','Documento','E-mail','Telefone','Status',''],[kind]); const totalPages=Math.max(1,Math.ceil(rows.length/pageSize));const visible=rows.slice((page-1)*pageSize,page*pageSize);
 return <><PageHeader title={c.title} subtitle={c.subtitle} actions={<button className="primary-button" disabled={!can(`${c.permission}.create`)} onClick={()=>{setEditing(null);setForm(initial(kind));setOpen(true)}}>+ Novo {c.single.toLowerCase()}</button>} />
 <Card><div className="toolbar"><div className="search"><span>⌕</span><input placeholder={`Buscar em ${c.title.toLowerCase()}...`} value={search} onChange={e=>setSearch(e.target.value)} /></div><div className="toolbar-right"><span className="record-count">{rows.length} registro{rows.length===1?'':'s'}</span><button className="ghost-button" onClick={load}>↻ Atualizar</button></div></div>{error&&<Alert>{error}</Alert>}{loading?<SkeletonTable/>:rows.length===0?<Empty text={search?'Nenhum resultado para esta busca.':'Nenhum cadastro encontrado.'}/>:<><div className="table-wrap"><table><thead><tr>{columns.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{visible.map(r=>kind==='products'?<tr key={r.id} className="clickable-row" onClick={()=>setDetail(r)}><td><strong>{r.name}</strong><small>{r.description||r.barcode||'-'}</small></td><td>{r.sku}</td><td>{r.unit}</td><td>{money(r.salePrice)}</td><td><Badge value={r.status}/></td><td><div className="row-actions" onClick={e=>e.stopPropagation()}><button className="table-action" onClick={()=>edit(r)} disabled={!can(`${c.permission}.update`)}>Editar</button><button className="table-action danger" onClick={()=>setRemove(r)} disabled={!can(`${c.permission}.delete`)}>Inativar</button></div></td></tr>:<tr key={r.id} className="clickable-row" onClick={()=>setDetail(r)}><td><strong>{r.name}</strong><small>{r.tradeName||r.legalName||r.type}</small></td><td>{r.document}</td><td>{r.email||'-'}</td><td>{r.phone||r.mobile||'-'}</td><td><Badge value={r.status}/></td><td><div className="row-actions" onClick={e=>e.stopPropagation()}><button className="table-action" onClick={()=>edit(r)} disabled={!can(`${c.permission}.update`)}>Editar</button><button className="table-action danger" onClick={()=>setRemove(r)} disabled={!can(`${c.permission}.delete`)}>Inativar</button></div></td></tr>)}</tbody></table></div><Pagination page={page} totalPages={totalPages} onPage={setPage}/></>}</Card>
 {open&&<div className="modal-backdrop" onMouseDown={closeForm}><div className="modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-header"><div><span className="eyebrow">{editing?'Editar cadastro':'Novo cadastro'}</span><h2>{c.single}</h2></div><button className="icon-button" onClick={closeForm}>×</button></div><form onSubmit={submit}><div className="form-grid">{c.fields.map(([key,label,type])=><label key={key}>{label}{type==='select'?<select value={form[key]||''} onChange={e=>setForm({...form,[key]:e.target.value})}><option value="INDIVIDUAL">Pessoa física</option><option value="BUSINESS">Pessoa jurídica</option></select>:type==='unit'?<select value={form[key]||'UN'} onChange={e=>setForm({...form,[key]:e.target.value})}>{['UN','KG','G','L','ML','CX','PC','M','M2','M3'].map(x=><option key={x}>{x}</option>)}</select>:<input type={type} value={form[key]??''} onChange={e=>setForm({...form,[key]:e.target.value})} required={['name','document','sku','unit'].includes(key)} />}</label>)}</div><div className="modal-actions"><button type="button" className="ghost-button" onClick={closeForm}>Cancelar</button><button className="primary-button">{editing?'Salvar alterações':'Salvar cadastro'}</button></div></form></div></div>}
 <DetailDrawer open={!!detail} title={detail?.name||c.single} onClose={()=>setDetail(null)}>{detail&&<div className="detail-list">{Object.entries(kind==='products'?{SKU:detail.sku,'Código de barras':detail.barcode||'-',Unidade:detail.unit,Custo:money(detail.costPrice),Venda:money(detail.salePrice),'Estoque mínimo':detail.minimumStock,Status:detail.status}:{Tipo:detail.type,Documento:detail.document,'E-mail':detail.email||'-',Telefone:detail.phone||detail.mobile||'-',Status:detail.status}).map(([k,v])=><div key={k}><span>{k}</span><strong>{String(v??'-')}</strong></div>)}</div>}</DetailDrawer>
 <ConfirmDialog open={!!remove} danger title={`Inativar ${c.single.toLowerCase()}?`} description={remove?`${remove.name} deixará de aparecer como ativo, mas o histórico será preservado.`:''} confirmLabel="Sim, inativar" onCancel={()=>setRemove(null)} onConfirm={removeRecord}/>
 </>;
}
