import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import { api } from '../lib/api';
import { useAuth } from '../context/AuthContext';
import { Alert, Badge, Card, Empty, PageHeader, Spinner } from '../components/Ui';

type Kind='customers'|'suppliers'|'products';
const configs={
  customers:{title:'Clientes',subtitle:'Cadastro e gestão da base de clientes',permission:'customers',endpoint:'/customers',fields:[['type','Tipo','select'],['name','Nome','text'],['document','CPF/CNPJ','text'],['email','E-mail','email'],['phone','Telefone','text']]},
  suppliers:{title:'Fornecedores',subtitle:'Cadastro de parceiros e fornecedores',permission:'suppliers',endpoint:'/suppliers',fields:[['type','Tipo','select'],['name','Nome','text'],['document','CPF/CNPJ','text'],['email','E-mail','email'],['phone','Telefone','text']]},
  products:{title:'Produtos',subtitle:'Catálogo de produtos, preços e estoque mínimo',permission:'products',endpoint:'/products',fields:[['name','Nome','text'],['sku','SKU','text'],['barcode','Código de barras','text'],['unit','Unidade','unit'],['costPrice','Custo','number'],['salePrice','Venda','number'],['minimumStock','Estoque mínimo','number']]}
} as const;
const initial=(kind:Kind)=>kind==='products'?{name:'',sku:'',barcode:'',unit:'UN',costPrice:'0',salePrice:'0',minimumStock:'0'}:{type:kind==='suppliers'?'BUSINESS':'INDIVIDUAL',name:'',document:'',email:'',phone:''};
export function MasterDataPage({kind}:{kind:Kind}){
 const c=configs[kind]; const {can}=useAuth(); const [rows,setRows]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [search,setSearch]=useState(''); const [open,setOpen]=useState(false); const [form,setForm]=useState<any>(()=>initial(kind)); const [error,setError]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');try{const q=search?`?search=${encodeURIComponent(search)}`:'';const r:any=await api(c.endpoint+q);setRows(r.data||r);}catch(e){setError(e instanceof Error?e.message:'Erro ao carregar.')}finally{setLoading(false)}},[c.endpoint,search]);
 useEffect(()=>{void load()},[load]);
 async function submit(e:FormEvent){e.preventDefault();setError('');try{const body:any={...form}; if(kind==='products'){for(const k of ['costPrice','salePrice','minimumStock']) body[k]=Number(body[k]||0); if(!body.barcode) delete body.barcode;} if(!body.email) delete body.email;if(!body.phone) delete body.phone;await api(c.endpoint,{method:'POST',body:JSON.stringify(body)});setOpen(false);setForm(initial(kind));await load();}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar.')}}
 const columns=useMemo(()=>kind==='products'?['Produto','SKU','Unidade','Preço','Status']:['Nome','Documento','E-mail','Telefone','Status'],[kind]);
 return <><PageHeader title={c.title} subtitle={c.subtitle} actions={<button className="primary-button" disabled={!can(`${c.permission}.create`)} onClick={()=>setOpen(true)}>+ Novo</button>} />
 <Card><div className="toolbar"><div className="search"><span>⌕</span><input placeholder={`Buscar em ${c.title.toLowerCase()}...`} value={search} onChange={e=>setSearch(e.target.value)} /></div><button className="ghost-button" onClick={load}>Atualizar</button></div>{error&&<Alert>{error}</Alert>}{loading?<Spinner/>:rows.length===0?<Empty/>:<div className="table-wrap"><table><thead><tr>{columns.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map(r=>kind==='products'?<tr key={r.id}><td><strong>{r.name}</strong><small>{r.description||r.barcode||'-'}</small></td><td>{r.sku}</td><td>{r.unit}</td><td>{Number(r.salePrice||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</td><td><Badge value={r.status}/></td></tr>:<tr key={r.id}><td><strong>{r.name}</strong><small>{r.tradeName||r.legalName||r.type}</small></td><td>{r.document}</td><td>{r.email||'-'}</td><td>{r.phone||r.mobile||'-'}</td><td><Badge value={r.status}/></td></tr>)}</tbody></table></div>}</Card>
 {open&&<div className="modal-backdrop" onMouseDown={()=>setOpen(false)}><div className="modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-header"><div><span className="eyebrow">Novo cadastro</span><h2>{c.title.slice(0,-1)}</h2></div><button className="icon-button" onClick={()=>setOpen(false)}>×</button></div><form onSubmit={submit}><div className="form-grid">{c.fields.map(([key,label,type])=><label key={key}>{label}{type==='select'?<select value={form[key]||''} onChange={e=>setForm({...form,[key]:e.target.value})}><option value="INDIVIDUAL">Pessoa física</option><option value="BUSINESS">Pessoa jurídica</option></select>:type==='unit'?<select value={form[key]||'UN'} onChange={e=>setForm({...form,[key]:e.target.value})}>{['UN','KG','G','L','ML','CX','PC','M','M2','M3'].map(x=><option key={x}>{x}</option>)}</select>:<input type={type} value={form[key]??''} onChange={e=>setForm({...form,[key]:e.target.value})} required={['name','document','sku','unit'].includes(key)} />}</label>)}</div><div className="modal-actions"><button type="button" className="ghost-button" onClick={()=>setOpen(false)}>Cancelar</button><button className="primary-button">Salvar</button></div></form></div></div>}
 </>;
}
