import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { Prisma } from '@prisma/client'; import { PrismaService } from '../../core/database/prisma.service';
import { CreatePurchaseRequestDto } from './dto/create-purchase-request.dto'; import { CreatePurchaseOrderDto } from './dto/create-purchase-order.dto'; import { ReceivePurchaseOrderDto } from './dto/receive-purchase-order.dto';
@Injectable() export class ProcurementService { constructor(private readonly prisma:PrismaService){}
 async createRequest(companyId:string,d:CreatePurchaseRequestDto){if(await this.prisma.purchaseRequest.findFirst({where:{companyId,number:d.number}}))throw new ConflictException('Número de requisição já existe.');const [b,p]=await Promise.all([this.prisma.branch.findFirst({where:{id:d.branchId,companyId,deletedAt:null}}),this.prisma.product.findMany({where:{companyId,id:{in:d.items.map(x=>x.productId)},deletedAt:null,status:'ACTIVE'}})]);if(!b||p.length!==new Set(d.items.map(x=>x.productId)).size)throw new NotFoundException('Filial ou produto inválido.');return this.prisma.purchaseRequest.create({data:{companyId,branchId:d.branchId,number:d.number,notes:d.notes,items:{create:d.items.map(x=>({productId:x.productId,quantity:new Prisma.Decimal(x.quantity),notes:x.notes}))}},include:{branch:true,items:{include:{product:true}}}})}
 async openRequest(companyId:string,id:string){const r=await this.prisma.purchaseRequest.findFirst({where:{id,companyId},include:{items:true}});if(!r)throw new NotFoundException('Requisição não encontrada.');if(r.status!=='DRAFT')throw new BadRequestException('Somente requisição em rascunho pode ser aberta.');return this.prisma.purchaseRequest.update({where:{id},data:{status:'OPEN'},include:{items:{include:{product:true}}}})}
 async listRequests(companyId:string){return this.prisma.purchaseRequest.findMany({where:{companyId},orderBy:{createdAt:'desc'},include:{branch:true,items:{include:{product:true}},orders:true}})}
 async createOrder(companyId:string,d:CreatePurchaseOrderDto){if(await this.prisma.purchaseOrder.findFirst({where:{companyId,number:d.number}}))throw new ConflictException('Número de pedido de compra já existe.');const [b,s,p,r]=await Promise.all([this.prisma.branch.findFirst({where:{id:d.branchId,companyId,deletedAt:null}}),this.prisma.supplier.findFirst({where:{id:d.supplierId,companyId,deletedAt:null,status:'ACTIVE'}}),this.prisma.product.findMany({where:{companyId,id:{in:d.items.map(x=>x.productId)},deletedAt:null,status:'ACTIVE'}}),d.requestId?this.prisma.purchaseRequest.findFirst({where:{id:d.requestId,companyId,status:{in:['OPEN','PARTIAL']}}}):Promise.resolve(null)]);if(!b||!s||p.length!==new Set(d.items.map(x=>x.productId)).size||(d.requestId&&!r))throw new NotFoundException('Filial, fornecedor, requisição ou produto inválido.');const items=d.items.map(x=>{const q=new Prisma.Decimal(x.quantity),c=new Prisma.Decimal(x.unitCost);return{productId:x.productId,quantity:q,unitCost:c,totalAmount:q.mul(c)}});const total=items.reduce((a,x)=>a.add(x.totalAmount),new Prisma.Decimal(0));return this.prisma.purchaseOrder.create({data:{companyId,branchId:d.branchId,supplierId:d.supplierId,requestId:d.requestId,number:d.number,notes:d.notes,totalAmount:total,items:{create:items}},include:{supplier:true,branch:true,items:{include:{product:true}}}})}
 async confirmOrder(companyId:string,id:string){const o=await this.prisma.purchaseOrder.findFirst({where:{id,companyId},include:{items:true}});if(!o)throw new NotFoundException('Pedido de compra não encontrado.');if(o.status!=='DRAFT')throw new BadRequestException('Pedido já processado.');return this.prisma.purchaseOrder.update({where:{id},data:{status:'CONFIRMED'},include:{items:{include:{product:true}},supplier:true}})}
 async listOrders(companyId:string){return this.prisma.purchaseOrder.findMany({where:{companyId},orderBy:{createdAt:'desc'},include:{supplier:true,branch:true,items:{include:{product:true}},receipts:true}})}
 async receive(companyId:string,id:string,d:ReceivePurchaseOrderDto){return this.prisma.$transaction(async tx=>{const o=await tx.purchaseOrder.findFirst({where:{id,companyId},include:{items:true}});if(!o)throw new NotFoundException('Pedido de compra não encontrado.');if(!['CONFIRMED','PARTIAL'].includes(o.status))throw new BadRequestException('Pedido não está disponível para recebimento.');const map=new Map(o.items.map(i=>[i.id,i]));for(const x of d.items){const item=map.get(x.purchaseOrderItemId);if(!item)throw new BadRequestException('Item não pertence ao pedido.');const q=new Prisma.Decimal(x.quantity),pending=item.quantity.sub(item.receivedQuantity);if(q.gt(pending))throw new BadRequestException('Quantidade recebida excede o saldo pendente.');let bal=await tx.inventoryBalance.findUnique({where:{branchId_productId:{branchId:o.branchId,productId:item.productId}}});if(!bal)bal=await tx.inventoryBalance.create({data:{companyId,branchId:o.branchId,productId:item.productId}});const prev=bal.quantity,current=prev.add(q);await tx.inventoryBalance.update({where:{id:bal.id},data:{quantity:current,available:bal.available.add(q)}});await tx.inventoryMovement.create({data:{companyId,branchId:o.branchId,productId:item.productId,type:'ENTRY',quantity:q,previousQty:prev,currentQty:current,referenceType:'PURCHASE_ORDER_RECEIPT',referenceId:o.id,notes:`Recebimento ${d.number}`}});await tx.purchaseOrderItem.update({where:{id:item.id},data:{receivedQuantity:{increment:q}}});}
 const receipt=await tx.goodsReceipt.create({data:{companyId,branchId:o.branchId,purchaseOrderId:o.id,number:d.number,notes:d.notes,items:{create:d.items.map(x=>({purchaseOrderItemId:x.purchaseOrderItemId,productId:map.get(x.purchaseOrderItemId)!.productId,quantity:new Prisma.Decimal(x.quantity)}))}},include:{items:{include:{product:true}}}});const fresh=await tx.purchaseOrderItem.findMany({where:{purchaseOrderId:o.id}});const done=fresh.every(i=>i.receivedQuantity.gte(i.quantity));await tx.purchaseOrder.update({where:{id:o.id},data:{status:done?'RECEIVED':'PARTIAL'}});return receipt;})}
 async pending(companyId:string){return this.prisma.purchaseOrder.findMany({where:{companyId,status:{in:['CONFIRMED','PARTIAL']}},include:{supplier:true,items:{include:{product:true}}},orderBy:{createdAt:'asc'}})} }
