import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common'; import { Prisma } from '@prisma/client'; import { PrismaService } from '../../core/database/prisma.service'; import { CreateSalesOrderDto } from './dto/create-sales-order.dto'; import { ListSalesOrdersQueryDto } from './dto/list-sales-orders-query.dto';
@Injectable() export class SalesOrdersService { constructor(private readonly prisma:PrismaService){}
private include(){return {branch:true,customer:true,paymentTerm:true,quote:true,sale:true,items:{include:{product:true}}} as const}
private items(items:CreateSalesOrderDto['items']){return items.map(i=>{const q=new Prisma.Decimal(i.quantity),p=new Prisma.Decimal(i.unitPrice),d=new Prisma.Decimal(i.discountAmount??0),g=q.mul(p);if(d.gt(g))throw new BadRequestException('Desconto maior que o item.');return{productId:i.productId,quantity:q,unitPrice:p,discountAmount:d,totalAmount:g.sub(d)}})}
async create(companyId:string,d:CreateSalesOrderDto){if(await this.prisma.salesOrder.findFirst({where:{companyId,number:d.number,deletedAt:null}}))throw new ConflictException('Número de pedido já existe.'); const [b,c,t,ps]=await Promise.all([this.prisma.branch.findFirst({where:{id:d.branchId,companyId,deletedAt:null}}),this.prisma.customer.findFirst({where:{id:d.customerId,companyId,status:'ACTIVE',deletedAt:null}}),d.paymentTermId?this.prisma.paymentTerm.findFirst({where:{id:d.paymentTermId,companyId,status:'ACTIVE',deletedAt:null}}):Promise.resolve(true),this.prisma.product.findMany({where:{id:{in:d.items.map(i=>i.productId)},companyId,status:'ACTIVE',deletedAt:null}})]); if(!b||!c||!t||ps.length!==new Set(d.items.map(i=>i.productId)).size)throw new NotFoundException('Filial, cliente, condição ou produto inválido.'); const items=this.items(d.items),total=items.reduce((a,i)=>a.add(i.totalAmount),new Prisma.Decimal(0));return this.prisma.salesOrder.create({data:{companyId,branchId:d.branchId,customerId:d.customerId,paymentTermId:d.paymentTermId,number:d.number,notes:d.notes,totalAmount:total,items:{create:items}},include:this.include()})}
async all(companyId:string,q:ListSalesOrdersQueryDto){const where:Prisma.SalesOrderWhereInput={companyId,deletedAt:null,...(q.status?{status:q.status}:{}),...(q.search?{number:{contains:q.search,mode:'insensitive'}}:{})};const [data,total]=await this.prisma.$transaction([this.prisma.salesOrder.findMany({where,skip:(q.page-1)*q.limit,take:q.limit,orderBy:{createdAt:'desc'},include:this.include()}),this.prisma.salesOrder.count({where})]);return{data,meta:{page:q.page,limit:q.limit,total,totalPages:Math.ceil(total/q.limit)}}}
async one(companyId:string,id:string){const r=await this.prisma.salesOrder.findFirst({where:{id,companyId,deletedAt:null},include:this.include()});if(!r)throw new NotFoundException('Pedido não encontrado.');return r}
async confirm(companyId:string,id:string){const r=await this.one(companyId,id);if(r.status!=='DRAFT')throw new BadRequestException('Pedido já processado.');return this.prisma.salesOrder.update({where:{id},data:{status:'CONFIRMED'},include:this.include()})}
async cancel(companyId:string,id:string){const r=await this.one(companyId,id);if(r.status==='CONVERTED')throw new BadRequestException('Pedido convertido em venda não pode ser cancelado.');return this.prisma.salesOrder.update({where:{id},data:{status:'CANCELLED'},include:this.include()})}
async convertToSale(companyId:string,id:string,saleNumber:string){const r=await this.one(companyId,id);if(r.status!=='CONFIRMED')throw new BadRequestException('Somente pedido confirmado pode virar venda.');if(r.sale)return r.sale;return this.prisma.$transaction(async tx=>{const sale=await tx.sale.create({data:{companyId,branchId:r.branchId,customerId:r.customerId,paymentTermId:r.paymentTermId,number:saleNumber,totalAmount:r.totalAmount,notes:r.notes,items:{create:r.items.map(i=>({productId:i.productId,quantity:i.quantity,unitPrice:i.unitPrice,discountAmount:i.discountAmount,totalAmount:i.totalAmount}))}},include:{items:true}});await tx.salesOrder.update({where:{id},data:{status:'CONVERTED',saleId:sale.id}});return sale;})}
}
